### PR TITLE
Introduce async init

### PR DESCRIPTION
**Pull request by thermatk**
I won't touch the loadEvents because it's easier to move it out to another thread than fix it for all possible cases with different durations.
Now one can extend dayitem, weekitem and calendarevent, prebuild a calendar with them and possibly persist them for quickly renewing the calendar next time, or just do initialization of calendar in a separate thread before creating the view.

### CODE REVIEW

**Comment by Tibolte** [comment]
@thermatk thanks for your contribution! I'm just having difficulties understanding what's new here. Could you maybe add a comment listing what are the bug fixes/features? :)

**Comment by thermatk** [comment]
I will, i have some additions coming to finally fully separate interfaces for calendarManager
The idea is that one can do buildCal and loadEvents for CalendarManager once and in the future just load a set of three lists. OnCreateView shouldn't do so much work, furthermore it can even be persisted in some way.
Compared to #43 I didn't tamper with the existing logic of doing everything in terms of calendars, because if the whole thing can be moved out and run async, I don't care that much about speed of this async anymore.
In my app I am downloading the list of events periodically via API and I want to add building of CalendarManager inside this task and persist the lists by implementing interfaces with RealmObjects, so that onCreateView will be fast.

**Comment by thermatk** [comment]
You can see the async way in the new MainActivity. I have commented out the currently used sync way and implemented the new one, but they both work. It's an addition which doesn't kill the previous functionality although I can't understand rebuilding calendar in the UI thread in onCreateView

**Comment by thermatk** [comment]
It's done for sure.
The comments are in commit messages, so except for the async work there is just some cleanup of never user Months and SparseArrayCompat got replaced by SparseArray because this way there is no need for support v4 and on the defined minapi+ the SparseArray is the same

**Comment by thermatk** [comment]
Should I add a full proper example with asynchronous calendar drawing? :)

**Comment by ArchitSandesara** [comment]
How to stay on the current selected date when the new data is added using async way?
I am facing issue when I add data async way the date changes to today automatically.
Below is the code I am using to add data async way.

  calendarManager = CalendarManager.getInstance(MainActivity.activity.getApplicationContext());
                                calendarManager.buildCal(minDate, maxDate, Locale.getDefault(), new DayItem(), new WeekItem());
                                calendarManager.loadEvents(eventList, new BaseCalendarEvent());
                                List<CalendarEvent> readyEvents = calendarManager.getEvents();
                                List<IDayItem> readyDays = calendarManager.getDays();
                                List<IWeekItem> readyWeeks = calendarManager.getWeeks();
                                mAgendaCalendarView.init( Locale.getDefault(), readyWeeks, readyDays, readyEvents, this);
                                mAgendaCalendarView.addEventRenderer(new DefaultEventRenderer());

**Pull request closed without merging**
