### PR TITLE
Change color on the Calendar

### PR DESCRIPTION
**Pull request by ftouh**
is it possible to change the color of a certain day in the calendar? (event days in different colors)

### CODE REVIEW

**Comment by Tibolte** [comment]
@ftouh can you tell me what is the purpose of this PR?

**Comment by ftouh** [comment]
to highlight the event days in the calendar (for example the event day will be in a different color on the calendar it so you could know the events available from the calendar not just from the list)

**Comment by Tibolte** [comment]
Ok I get the idea :) I'm not sure where are the changes related to that feature in this PR here. @ftouh can you point me to the code you changed that enables that new feature?

**Comment by ftouh** [comment]
i didin't change anything i'm sorry at first i was asking if this feature is available or not i thought this was some kind of a forum you can delete this branch and maybe in the feature where i will add this feature i will create this PR

**Comment by Tibolte** [comment]
Ok get it, in that case I would suggest creating an issue [here](https://github.com/Tibolte/AgendaCalendarView/issues).

No worries, you'll get the idea about github soon :)

**Pull request closed without merging**
