### PR TITLE
Remove weather code

### PR DESCRIPTION
**Pull request by thermatk**
Couldn't see how it is currently used, there even was a TODO to remove it.
AgendaCalendarView is still being created very slow, investigating further :)

### CODE REVIEW

**Comment by Tibolte** [comment]
Awesome!! That's something to be done indeed. Also, what do you mean by "still being created very slow"?

**Comment by thermatk** [comment]
@Tibolte I have actually found the slowest place ever, three nested FOR cycles in loadEvents.
I am trying to rewrite to HashMap.
My usecase is calendar for a year with 100+ events, your code results in more than 365*100 simple iterations. HashMap should be more like 366 just a bit more complex :)

**Comment by Tibolte** [comment]
@thermatk good catch, that's good feedback!

**Comment by Tibolte** [comment]
@thermatk as you're on that topic, would you mind creating an issue for that issue you just discovered?

**Pull request merged**
